import type { Locale } from '@/lib/routes';
import { site } from '@/lib/site';

export const serviceIds = ['packshots', 'lifestyle', 'animation'] as const;
export type ServiceId = (typeof serviceIds)[number];

export const budgetIds = ['lt500', '500-1500', '1500-3000', 'gt3000', 'unknown'] as const;
export type BudgetId = (typeof budgetIds)[number];

const years = site.blenderYears;

export const copy = {
  es: {
    meta: {
      title: 'ViewportStudio3D — Renders 3D de producto para marcas que venden online',
      description:
        'Estudio de render 3D de producto de Lucas Expósito. Packshots para e-commerce, escenas lifestyle y animaciones hechas en Blender, sin sesión de fotos.',
    },
    a11y: {
      skip: 'Saltar al contenido',
      menuOpen: 'Abrir menú',
      menuClose: 'Cerrar menú',
      mainNav: 'Navegación principal',
      language: 'Idioma',
      switchTo: 'Ver en inglés',
      play: 'Reproducir animación',
      pause: 'Pausar animación',
      backToTop: 'Volver arriba',
    },
    nav: {
      work: 'Trabajo',
      services: 'Servicios',
      process: 'Proceso',
      about: 'Sobre mí',
      faq: 'FAQ',
      contact: 'Contacto',
      cta: 'Pedir presupuesto',
      ctaShort: 'Presupuesto',
    },
    hero: {
      eyebrow: 'Estudio de render 3D de producto',
      eyebrowSide: 'Blender · España',
      title: 'Renders 3D de producto para marcas que venden online.',
      lead: 'Packshots, escenas y animaciones hechas en Blender. Sin sesión de fotos y con cada variante lista para tu tienda y tus anuncios.',
      primary: 'Pedir presupuesto',
      secondary: 'Ver caso Fine Nipona',
      response: `Respondo en ${site.responseTime.es}`,
      imageAlt: 'Render 3D de un smartphone de la marca ficticia pPhone sobre fondo negro.',
    },
    problem: {
      label: 'Por qué 3D',
      statement: 'Buenos productos, vendidos con imágenes que no están a su altura. El render 3D lo cambia.',
      points: [
        {
          title: 'Todo el catálogo, coherente',
          text: 'La misma luz, el mismo ángulo y el mismo acabado en cada ficha, aunque lances productos con meses de diferencia.',
        },
        {
          title: 'Variantes sin repetir sesión',
          text: 'Un color, un sabor o un tamaño nuevo se resuelve sobre el mismo modelo 3D, sin volver a fotografiar.',
        },
        {
          title: 'Un modelo, todos los formatos',
          text: 'Del mismo proyecto salen el packshot de la tienda, la imagen de campaña y la animación para anuncios.',
        },
      ],
      studio: {
        title: 'Pruébalo: un modelo, cinco acabados.',
        hint: 'Arrastra para girar el pPhone 17 y cambia su color. Así se resuelven las variantes de un catálogo: sobre el mismo modelo, sin volver a fotografiar.',
        hud: 'Vista en tiempo real',
        note: 'Modelo simplificado para el navegador. El render final tiene más detalle, luz de estudio y postproducción.',
        finish: 'Acabado',
        stageLabel: 'Modelo 3D interactivo del pPhone 17. Arrastra o usa las flechas del teclado para girarlo.',
        reset: 'Centrar vista',
        colors: { lila: 'Lila', azul: 'Azul', grafito: 'Grafito', verde: 'Verde', plata: 'Plata' },
      },
    },
    work: {
      label: 'Trabajo seleccionado',
      title: 'Luz, material y movimiento al servicio del producto.',
      intro: 'Del envase de un matcha premium al lanzamiento de un smartphone: así trabajo cada pieza.',
      viewCase: 'Ver caso',
      cursor: 'Ver caso',
    },
    services: {
      label: 'Servicios',
      title: 'Tres formas de presentar mejor tu producto.',
      includes: 'Incluye',
      timing: 'Plazo',
      cta: 'Pedir presupuesto',
      items: {
        packshots: {
          name: 'Packshots para e-commerce',
          text: 'Tu producto aislado, con luz de estudio y fondo neutro, listo para la ficha de tu tienda y los marketplaces.',
          includes: ['Fondo neutro o del color de tu marca', 'Varios ángulos por producto', 'Variantes de color, sabor o tamaño'],
          timing: '3–5 días laborables',
          mediaAlt: 'Packshot 3D de la bolsa blanca de Matcha de Fine Nipona sobre fondo oscuro de estudio.',
        },
        lifestyle: {
          name: 'Escenas lifestyle y campaña',
          text: 'Tu producto dentro de un ambiente que cuenta la historia de tu marca: materiales, luz y atmósfera a medida.',
          includes: ['Dirección de arte de la escena', 'Composición para web, redes y campaña', 'Formatos horizontal, cuadrado y vertical'],
          timing: '1–2 semanas',
          mediaAlt: 'Escena 3D con la bolsa negra de Mulberry Matcha de Fine Nipona sobre piedra, con luz rasante y un cuenco de madera.',
        },
        animation: {
          name: 'Animación de producto',
          text: 'Vídeos cortos para lanzamientos, anuncios y redes: el producto se mueve, se acerca y enseña cada detalle.',
          includes: ['Guion de planos', 'Formatos 9:16 y 16:9', 'Loops para web y anuncios'],
          timing: '2–4 semanas',
          mediaAlt: 'Animación 3D vertical de las dos bolsas de Fine Nipona, Matcha y Mulberry Matcha.',
        },
      } satisfies Record<ServiceId, unknown>,
    },
    process: {
      label: 'Proceso',
      title: 'Así trabajamos juntos.',
      youSend: 'Tú envías',
      youGet: 'Recibes',
      steps: [
        {
          title: 'Brief',
          send: 'fotos o planos del producto, el diseño del envase y referencias de estilo.',
          get: 'propuesta de planos, plazo y presupuesto cerrado.',
        },
        {
          title: 'Modelo y materiales',
          send: null,
          get: 'una vista previa del modelo para validar forma, etiquetas y acabados antes de iluminar.',
        },
        {
          title: 'Luz y render',
          send: null,
          get: 'las primeras imágenes o la animación, con dos rondas de revisión incluidas.',
        },
        {
          title: 'Entrega',
          send: null,
          get: 'los archivos finales en los formatos que necesites para tienda, web, redes y anuncios.',
        },
      ],
    },
    about: {
      label: 'Sobre mí',
      title: 'Trabajas directamente conmigo.',
      paragraphs: [
        `Soy ${site.founder}, fundador de ViewportStudio3D. Llevo más de ${years} años creando en Blender y me he especializado en el render de producto.`,
        'Me formé en diseño gráfico y en sistemas microinformáticos y redes: por eso cuido tanto la composición de cada imagen como la parte técnica de cada escena.',
        'Trabajo con mucha pasión en cada proyecto y mi objetivo es siempre el mismo: que acabes muy satisfecho con el resultado.',
      ],
      facts: [
        { term: 'Fundador', value: site.founder },
        { term: 'Experiencia', value: `Más de ${years} años con Blender` },
        { term: 'Formación', value: 'Diseño gráfico · Sistemas microinformáticos y redes' },
        { term: 'Herramientas', value: site.tools.join(', ') },
        { term: 'Ubicación', value: 'España' },
      ],
      mediaAlt: 'Primer plano en 3D de la bolsa negra de Mulberry Matcha de Fine Nipona, con el mapa de Japón en puntos rojos.',
    },
    testimonials: { label: 'Clientes', title: 'Lo que dicen de trabajar conmigo.' },
    faq: {
      label: 'Preguntas frecuentes',
      title: 'Antes de escribirme.',
      items: [
        {
          q: '¿Cuánto cuesta un proyecto?',
          a: 'Depende de cuántas imágenes o segundos de animación necesites, de la complejidad del producto y de la escena. En el formulario puedes indicar un presupuesto orientativo y te envío un presupuesto cerrado, sin compromiso.',
        },
        {
          q: '¿Cuánto tardas en entregar?',
          a: 'Packshots para e-commerce: 3–5 días laborables. Escenas lifestyle y de campaña: 1–2 semanas. Animación de producto: 2–4 semanas. Los plazos cuentan desde que tengo todo el material del producto.',
        },
        {
          q: '¿Cuántas revisiones incluye?',
          a: 'Cada proyecto incluye dos rondas de revisión, para que puedas ajustar encuadres, materiales o luz antes de la entrega final.',
        },
        {
          q: '¿Qué necesito enviarte?',
          a: 'Fotos del producto desde varios ángulos, sus medidas y el diseño del envase o la etiqueta (PDF o archivo vectorial) si lo tienes. Si existe un modelo 3D o CAD, mejor todavía.',
        },
        {
          q: '¿En qué formatos entregas?',
          a: 'Imágenes en alta resolución (PNG o JPG) y animaciones en MP4, en el formato que necesites: horizontal, cuadrado o vertical 9:16.',
        },
        {
          q: '¿Puedo usar las imágenes en mi tienda y en anuncios?',
          a: 'Sí. El uso en tu web, tienda online, redes sociales y publicidad está incluido. Si necesitas condiciones especiales, las concretamos en el presupuesto.',
        },
      ],
    },
    contact: {
      label: 'Contacto',
      title: 'Cuéntame tu producto.',
      intro: `Te respondo en ${site.responseTime.es} con dudas concretas o con un presupuesto cerrado.`,
      emailLabel: '¿Prefieres escribirme directamente?',
      copy: 'Copiar',
      copied: 'Copiado',
      fields: {
        name: 'Nombre',
        email: 'Email',
        company: 'Marca o empresa',
        service: '¿Qué necesitas?',
        budget: 'Presupuesto orientativo',
        message: 'Cuéntame el proyecto',
        messagePlaceholder: 'Qué producto es, cuántas imágenes o segundos de animación necesitas y para cuándo.',
        consentBefore: 'He leído la ',
        consentLink: 'política de privacidad',
        consentAfter: ' y acepto que uses mis datos para responder a mi consulta.',
        optional: 'opcional',
        required: 'obligatorio',
        website: 'Deja este campo vacío',
      },
      serviceOptions: {
        packshots: 'Packshots para e-commerce',
        lifestyle: 'Escenas lifestyle y campaña',
        animation: 'Animación de producto',
        unknown: 'Aún no lo sé',
      },
      budgetOptions: {
        lt500: 'Menos de 500 €',
        '500-1500': '500–1.500 €',
        '1500-3000': '1.500–3.000 €',
        gt3000: 'Más de 3.000 €',
        unknown: 'Aún no lo sé',
      } satisfies Record<BudgetId, string>,
      submit: 'Enviar consulta',
      sending: 'Enviando…',
      errors: {
        name: 'Escribe tu nombre.',
        email: 'Escribe un email válido.',
        message: 'Cuéntame un poco más (mínimo 10 caracteres).',
        consent: 'Necesito tu consentimiento para responderte.',
        tooLong: 'El texto es demasiado largo.',
        summary: 'Revisa los campos marcados.',
        rate: 'Has enviado varias consultas seguidas. Espera unos minutos o escríbeme por email.',
        server: 'No se ha podido enviar el mensaje. Escríbeme directamente y te respondo igual de rápido:',
        unavailable: 'El envío automático no está disponible ahora mismo. Tu mensaje está listo para enviarlo desde tu correo:',
        openMail: 'Abrir en mi correo',
      },
      success: {
        title: 'Mensaje enviado.',
        text: (email: string) => `Te respondo en ${site.responseTime.es} en ${email}.`,
        again: 'Enviar otra consulta',
      },
    },
    footer: {
      tagline: 'Estudio de render 3D de producto, fundado por Lucas Expósito.',
      navTitle: 'Navegación',
      contactTitle: 'Contacto',
      legalTitle: 'Legal',
      legal: 'Aviso legal',
      privacy: 'Privacidad',
      rights: 'Todos los derechos reservados.',
    },
    project: {
      breadcrumb: 'Trabajo',
      type: 'Tipo',
      sector: 'Sector',
      deliverables: 'Entregables',
      tools: 'Herramientas',
      formats: 'Formatos',
      gallery: 'Galería',
      approach: 'Cómo lo planteé',
      updated: 'Última actualización',
      next: 'Siguiente proyecto',
      ctaTitle: '¿Tienes un producto que presentar?',
      ctaText: `Cuéntame qué necesitas y te respondo en ${site.responseTime.es}.`,
      cta: 'Pedir presupuesto',
      backToWork: 'Volver al trabajo',
    },
    notFound: {
      title: 'Esta página no existe.',
      text: 'Puede que el enlace haya cambiado. Vuelve al inicio o mira el trabajo seleccionado.',
      home: 'Ir al inicio',
      work: 'Ver trabajo',
    },
  },

  en: {
    meta: {
      title: 'ViewportStudio3D — 3D product renders for brands that sell online',
      description:
        '3D product rendering studio by Lucas Expósito. E-commerce packshots, lifestyle scenes and product animations made in Blender — no photoshoot needed.',
    },
    a11y: {
      skip: 'Skip to content',
      menuOpen: 'Open menu',
      menuClose: 'Close menu',
      mainNav: 'Main navigation',
      language: 'Language',
      switchTo: 'View in Spanish',
      play: 'Play animation',
      pause: 'Pause animation',
      backToTop: 'Back to top',
    },
    nav: {
      work: 'Work',
      services: 'Services',
      process: 'Process',
      about: 'About',
      faq: 'FAQ',
      contact: 'Contact',
      cta: 'Get a quote',
      ctaShort: 'Quote',
    },
    hero: {
      eyebrow: '3D product rendering studio',
      eyebrowSide: 'Blender · Spain',
      title: '3D product renders for brands that sell online.',
      lead: 'Packshots, scenes and animations made in Blender. No photoshoot, and every variant ready for your store and your ads.',
      primary: 'Get a quote',
      secondary: 'See the Fine Nipona case',
      response: `I reply within ${site.responseTime.en}`,
      imageAlt: '3D render of a smartphone from the fictional pPhone brand on a black background.',
    },
    problem: {
      label: 'Why 3D',
      statement: 'Great products, sold with images that don’t do them justice. 3D rendering changes that.',
      points: [
        {
          title: 'A consistent catalogue',
          text: 'The same light, angle and finish on every product page, even when launches are months apart.',
        },
        {
          title: 'Variants without a reshoot',
          text: 'A new colour, flavour or size is handled on the same 3D model — no need to photograph it again.',
        },
        {
          title: 'One model, every format',
          text: 'The same project delivers your store packshot, your campaign image and your ad animation.',
        },
      ],
      studio: {
        title: 'Try it: one model, five finishes.',
        hint: 'Drag to turn the pPhone 17 and change its colour. This is how catalogue variants are handled: on the same model, without another photoshoot.',
        hud: 'Real-time view',
        note: 'Simplified model for the browser. The final render has more detail, studio lighting and post-production.',
        finish: 'Finish',
        stageLabel: 'Interactive 3D model of the pPhone 17. Drag or use the arrow keys to turn it.',
        reset: 'Reset view',
        colors: { lila: 'Lilac', azul: 'Blue', grafito: 'Graphite', verde: 'Green', plata: 'Silver' },
      },
    },
    work: {
      label: 'Selected work',
      title: 'Light, material and motion in service of the product.',
      intro: 'From a premium matcha pouch to a smartphone launch: this is how I approach every piece.',
      viewCase: 'View case',
      cursor: 'View case',
    },
    services: {
      label: 'Services',
      title: 'Three ways to present your product better.',
      includes: 'Includes',
      timing: 'Timeline',
      cta: 'Get a quote',
      items: {
        packshots: {
          name: 'E-commerce packshots',
          text: 'Your product isolated, with studio lighting and a neutral background, ready for your product page and marketplaces.',
          includes: ['Neutral or brand-colour background', 'Several angles per product', 'Colour, flavour or size variants'],
          timing: '3–5 working days',
          mediaAlt: '3D packshot of the white Fine Nipona Matcha pouch on a dark studio background.',
        },
        lifestyle: {
          name: 'Lifestyle & campaign scenes',
          text: 'Your product inside a setting that tells your brand’s story: custom materials, light and atmosphere.',
          includes: ['Scene art direction', 'Compositions for web, social and campaigns', 'Landscape, square and vertical formats'],
          timing: '1–2 weeks',
          mediaAlt: '3D scene with the black Fine Nipona Mulberry Matcha pouch on stone, with raking light and a wooden bowl.',
        },
        animation: {
          name: 'Product animation',
          text: 'Short videos for launches, ads and social: the product moves, comes closer and shows every detail.',
          includes: ['Shot list', '9:16 and 16:9 formats', 'Loops for web and ads'],
          timing: '2–4 weeks',
          mediaAlt: 'Vertical 3D animation of the two Fine Nipona pouches, Matcha and Mulberry Matcha.',
        },
      } satisfies Record<ServiceId, unknown>,
    },
    process: {
      label: 'Process',
      title: 'How we work together.',
      youSend: 'You send',
      youGet: 'You get',
      steps: [
        {
          title: 'Brief',
          send: 'photos or drawings of the product, the packaging design and style references.',
          get: 'a shot proposal, timeline and fixed quote.',
        },
        {
          title: 'Model & materials',
          send: null,
          get: 'a model preview to approve shape, labels and finishes before lighting.',
        },
        {
          title: 'Light & render',
          send: null,
          get: 'the first images or the animation, with two rounds of revisions included.',
        },
        {
          title: 'Delivery',
          send: null,
          get: 'final files in the formats you need for your store, website, social and ads.',
        },
      ],
    },
    about: {
      label: 'About',
      title: 'You work directly with me.',
      paragraphs: [
        `I’m ${site.founder}, founder of ViewportStudio3D. I’ve been creating in Blender for more than ${years} years and I specialise in product rendering.`,
        'I trained in graphic design and in computer systems and networks, so I care as much about the composition of every image as about the technical side of every scene.',
        'I put a lot of passion into every project, and my goal is always the same: that you end up truly happy with the result.',
      ],
      facts: [
        { term: 'Founder', value: site.founder },
        { term: 'Experience', value: `${years}+ years with Blender` },
        { term: 'Training', value: 'Graphic design · Computer systems and networks' },
        { term: 'Tools', value: site.tools.join(', ') },
        { term: 'Based in', value: 'Spain' },
      ],
      mediaAlt: '3D close-up of the black Fine Nipona Mulberry Matcha pouch, with the map of Japan in red dots.',
    },
    testimonials: { label: 'Clients', title: 'What clients say about working with me.' },
    faq: {
      label: 'FAQ',
      title: 'Before you write.',
      items: [
        {
          q: 'How much does a project cost?',
          a: 'It depends on how many images or seconds of animation you need, and on the complexity of the product and the scene. Pick an indicative budget in the form and I’ll send you a fixed quote, with no commitment.',
        },
        {
          q: 'How long does delivery take?',
          a: 'E-commerce packshots: 3–5 working days. Lifestyle and campaign scenes: 1–2 weeks. Product animation: 2–4 weeks. Timelines start once I have all the product material.',
        },
        {
          q: 'How many revisions are included?',
          a: 'Every project includes two rounds of revisions, so you can adjust framing, materials or lighting before final delivery.',
        },
        {
          q: 'What do I need to send you?',
          a: 'Photos of the product from several angles, its dimensions and the packaging or label design (PDF or vector file) if you have it. A 3D or CAD model is even better.',
        },
        {
          q: 'Which formats do you deliver?',
          a: 'High-resolution images (PNG or JPG) and animations in MP4, in the format you need: landscape, square or vertical 9:16.',
        },
        {
          q: 'Can I use the images in my store and in ads?',
          a: 'Yes. Use on your website, online store, social media and advertising is included. If you need special terms, we set them out in the quote.',
        },
      ],
    },
    contact: {
      label: 'Contact',
      title: 'Tell me about your product.',
      intro: `I reply within ${site.responseTime.en} with specific questions or a fixed quote.`,
      emailLabel: 'Prefer to email me directly?',
      copy: 'Copy',
      copied: 'Copied',
      fields: {
        name: 'Name',
        email: 'Email',
        company: 'Brand or company',
        service: 'What do you need?',
        budget: 'Indicative budget',
        message: 'Tell me about the project',
        messagePlaceholder: 'What the product is, how many images or seconds of animation you need, and by when.',
        consentBefore: 'I have read the ',
        consentLink: 'privacy policy',
        consentAfter: ' and agree that you use my data to reply to my enquiry.',
        optional: 'optional',
        required: 'required',
        website: 'Leave this field empty',
      },
      serviceOptions: {
        packshots: 'E-commerce packshots',
        lifestyle: 'Lifestyle & campaign scenes',
        animation: 'Product animation',
        unknown: 'Not sure yet',
      },
      budgetOptions: {
        lt500: 'Under €500',
        '500-1500': '€500–1,500',
        '1500-3000': '€1,500–3,000',
        gt3000: 'Over €3,000',
        unknown: 'Not sure yet',
      } satisfies Record<BudgetId, string>,
      submit: 'Send enquiry',
      sending: 'Sending…',
      errors: {
        name: 'Please enter your name.',
        email: 'Please enter a valid email.',
        message: 'Tell me a bit more (at least 10 characters).',
        consent: 'I need your consent to reply.',
        tooLong: 'This text is too long.',
        summary: 'Please check the highlighted fields.',
        rate: 'You’ve sent several enquiries in a row. Wait a few minutes or email me.',
        server: 'Your message couldn’t be sent. Email me directly and I’ll reply just as fast:',
        unavailable: 'Automatic sending isn’t available right now. Your message is ready to send from your email app:',
        openMail: 'Open in my email app',
      },
      success: {
        title: 'Message sent.',
        text: (email: string) => `I’ll reply within ${site.responseTime.en} at ${email}.`,
        again: 'Send another enquiry',
      },
    },
    footer: {
      tagline: '3D product rendering studio, founded by Lucas Expósito.',
      navTitle: 'Navigation',
      contactTitle: 'Contact',
      legalTitle: 'Legal',
      legal: 'Legal notice',
      privacy: 'Privacy',
      rights: 'All rights reserved.',
    },
    project: {
      breadcrumb: 'Work',
      type: 'Type',
      sector: 'Sector',
      deliverables: 'Deliverables',
      tools: 'Tools',
      formats: 'Formats',
      gallery: 'Gallery',
      approach: 'The approach',
      updated: 'Last updated',
      next: 'Next project',
      ctaTitle: 'Have a product to present?',
      ctaText: `Tell me what you need and I’ll reply within ${site.responseTime.en}.`,
      cta: 'Get a quote',
      backToWork: 'Back to work',
    },
    notFound: {
      title: 'This page doesn’t exist.',
      text: 'The link may have changed. Go back home or have a look at the selected work.',
      home: 'Go home',
      work: 'See work',
    },
  },
} as const;

export type Copy = (typeof copy)[Locale];

export function t(locale: Locale): Copy {
  return copy[locale] as Copy;
}
